version: '3'

services:
  selenium:
    image: selenium/standalone-chrome-debug
    shm_size: 2g
    ports:
      - 4444:4444
      - 5900:5900
  cookie_monster:
    build: ./cookie-monster
    volumes:
      - ./cookie-monster:/usr/src/app
    ports:
      - 4080:4080
      - 4443:4443
    networks:
      default:
        aliases:
          - not_the_cookie_monster
  start_dependencies:
    image: dadarek/wait-for-dependencies
    depends_on:
      - selenium
      - cookie_monster
    command: selenium:4444 cookie_monster:4080 not_the_cookie_monster:4080
  tests:
    build: .
    volumes:
      - .:/usr/src/app
    command: [ "npm", "test", "--", "--watch"]