version: '3'

services:
  selenium:
    image: selenium/standalone-chrome-debug
    shm_size: 2g
    ports:
      - 4444:4444
      - 5900:5900
  start_dependencies:
    image: dadarek/wait-for-dependencies
    depends_on:
      - selenium
    command: selenium:4444
  tests:
    build: .
    volumes:
      - .:/usr/src/app